steps:
  - id: dockerize-garner-ssh-gateway
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/garner-ssh-gateway:$COMMIT_SHA-rc
      - .
images:
  - gcr.io/$PROJECT_ID/garner-ssh-gateway:$COMMIT_SHA-rc
