apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-gateway.fullname" . }}
  labels:
    {{- include "ssh-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPortName }}
      protocol: TCP
      name: {{ .Values.containerPortName }}
  selector:
    {{- include "ssh-gateway.selectorLabels" . | nindent 4 }}